services:
  # database
  mariadb:
    image: "mariadb:latest"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
      MARIADB_ROOT_PASSWORD: "" # voor lokaal gebruik zetten we het root wachtwoord op leeg

  phpmyadmin:
    image: "phpmyadmin"
    ports:
      - "127.0.0.1:8081:80" # phpMyAdmin is lokaal toegankelijk vanaf poort 8081
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb # dit geeft aan dat dit de container is waarop de database runt.