### Upload Game pictures by urls
< {%
    request.variables.set("gameId", 1)
%}
POST http://localhost:8080/games/{{gameId}}/pictures
Content-Type: application/json

{
  "pictureData": ["https://google.com"]
}

### Get topscores from a game
< {%
    request.variables.set("gameId", 2)
%}

GET http://localhost:8080/games/{{gameId}}/leaderboard
Accept: application/json

### upload new game
POST http://localhost:8080/games
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "DanceDanceRevolution",
  "description": "A real-time dancing game with cool electronic beats!",
  "publisher": "Konami"
}

### edit game
< {%
    request.variables.set("gameId", 6)
%}
PATCH http://localhost:8080/games/{{gameId}}
Content-Type: application/json

{
  "releaseDate": "1999-01-01"
}