### Create game session
POST http://localhost:8080/sessions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "gameId": "1",
  "userId": "4",
  "visibility": 0
}

### Upload end of session picture
< {%
    request.variables.set("sessionId", "019a1217-6cca-75c4-acce-ea5bcb30ba54") // update sessionId with current sessionId
%}
PATCH http://localhost:8080/sessions/{{sessionId}}/picture
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "pictureUrl": "https://picsum.photos/256/256"
}

### Update session
< {%
    request.variables.set("sessionId", "019a1217-6cca-75c4-acce-ea5bcb30ba54") // update sessionId with current sessionId
%}
PATCH http://localhost:8080/sessions/{{sessionId}}
Content-Type: application/json
Authorization: bearer {{auth_token}}

{
  "endTime": "{{$isoTimestamp}}",
  "visibility": 4
}

### Delete session
< {%
    request.variables.set("sessionId", "019a1217-6cca-75c4-acce-ea5bcb30ba54") // update sessionId with current sessionId
%}
DELETE http://localhost:8080/sessions/{{sessionId}}
Content-Type: application/json
Authorization: bearer {{auth_token}}


### get scores for session
< {%
    request.variables.set("sessionId", "53582ea1-b02c-11f0-a5e6-6e5509172b8d") // update sessionId with current sessionId
%}
GET http://localhost:8080/sessions/{{sessionId}}/scores
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### upload score to session
< {%
    request.variables.set("sessionId", "53582ea1-b02c-11f0-a5e6-6e5509172b8d") // update sessionId with current sessionId
%}
// make sure the session has ended before you post scores
POST http://localhost:8080/sessions/{{sessionId}}/scores
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[
    {
      "score": 10.0,
      "turn": 0,
      "sessionPlayer": {
        "userId": 1,
        "guest": "guest2"
      }
    }
]

### get score from specific session
< {%
    request.variables.set("sessionId", "53582ea1-b02c-11f0-a5e6-6e5509172b8d") // update sessionId with current sessionId
    request.variables.set("scoreId", "019a122c-3f02-7db4-8e66-42805a0218ce") // update scoreId with current scoreId that is linked to the sessionId
%}
GET http://localhost:8080/sessions/{{sessionId}}/scores/{{scoreId}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### update score
< {%
    request.variables.set("sessionId", "53582ea1-b02c-11f0-a5e6-6e5509172b8d") // update sessionId with current sessionId
    request.variables.set("scoreId", "019a122c-3f02-7db4-8e66-42805a0218ce") // update scoreId with current scoreId that is linked to the sessionId
%}
PATCH http://localhost:8080/sessions/{{sessionId}}/scores/{{scoreId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "score": 100.0,
  "turn": 0
}