### get a list of all users
GET http://localhost:8080/users

### get a list of all users with query-params
GET http://localhost:8080/users?limit=10&offset=0&query=min

### get user with id '1'
@id = 1
GET http://localhost:8080/users/{{id}}

###
GET http://localhost:8080/users/s

### register new user
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "Bob",
  "email": "bob@connect-play.nl",
  "password": "Pass1234"
}