### get a list of all users
GET http://localhost:8080/users

### get a list of all users with query-params
GET http://localhost:8080/users?limit=10&offset=5&query=

### get user with id '1'
@id = 1
GET http://localhost:8080/users/{{id}}

### register new user
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "Bob",
  "email": "bob@connect-play.nl",
  "password": "Pass1234"
}

### friend request
POST http://localhost:8080/users/{{id}}/friends
Content-Type: application/json

{
  "friendId": 2
}