# This is for all friends endpoint inside of the users endpoint

### send friend request
< {%
    request.variables.set("userId", 4) // as user 4
    request.variables.set("friendId", 3) // send a friend request to user 2
%}
POST http://localhost:8080/users/{{userId}}/friends
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "friendId": {{friendId}}
}

### get friends
< {%
    request.variables.set("userId", 4) // gets friends for user 4
%}
GET http://localhost:8080/users/{{userId}}/friends
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get friend reqs
< {%
    request.variables.set("userId", 4) // gets friends for user 4
%}
GET http://localhost:8080/users/me/friendrequests
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### accept friend request
< {%
    request.variables.set("userId", 2) // as user 2
    request.variables.set("friendId", 4) // accept friend request from user 4
%}
PATCH http://localhost:8080/users/{{userId}}/friends/{{friendId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "accept": true
}

### deny friend request
< {%
    request.variables.set("userId", 2) // as user 2
    request.variables.set("friendId", 4) // deny friend request from user 4
%}
PATCH http://localhost:8080/users/{{userId}}/friends/{{friendId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "accept": false
}

### remove user as friend
< {%
    request.variables.set("userId", 2) // as user 2
    request.variables.set("friendId", 4) // remove friendship from user 4
%}
DELETE http://localhost:8080/users/{{userId}}/friends/{{friendId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get followed gamelist
< {%
    request.variables.set("userId", 4)
%}
GET http://localhost:8080/users/{{userId}}/followed?offset=0&limit=10
Accept: application/json
Authorization: Bearer {{auth_token}}

### Follow a game with authorisation
// this block is a pre-request script and it set a variable before sending the request
< {%
    request.variables.set("gameId", "5");
%}
POST http://localhost:8080/games/{{gameId}}/follow
Accept: application/json
Authorization: Bearer {{auth_token}}

### Unfollow a game with authorisation
< {%
    request.variables.set("gameId", "5");
%}

DELETE http://localhost:8080/games/{{gameId}}/unfollow
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get followers of a game
< {%
    request.variables.set("gameId", "5");
%}

GET http://localhost:8080/games/{{gameId}}/followers?offset=0&limit=10
Accept: application/json
Authorization: Bearer {{auth_token}}
