### register new user
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "Bob",
  "email": "bob@connect-play.nl",
  "password": "Pass1234"
}

### log in
POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
  "email": "bob@connect-play.nl",
  "password": "Pass1234"
}

> {%
    // so you don't have to manually update the token
    // but set your environment to 'dev' otherwise it won't work
    client.global.set("auth_token", response.body.token);
%}