# This is for all the users and auth endpoints

### get a list of all users
GET http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get a list of all users with query-params
GET http://localhost:8080/users?limit=10&offset=0&query=Bob
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get user with id '1'
# this is a pre-request script
< {%
    request.variables.set("userId", 1) // this is a per-request variable
%}
GET http://localhost:8080/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Upload a new profile picture with an file
< {%
    request.variables.set("userId", 1)
%}
PATCH http://localhost:8080/users/{{userId}}/picture
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{auth_token}}

--boundary
Content-Disposition: form-data; name="profile-picture"; filename="picture2.jpg"
Content-Type: image/jpeg

# route to the picture
< ../../../../../resources/picture.jpg
--boundary--

### Upload an new profile picture with an URL
< {%
    request.variables.set("userId", 1)
%}
PATCH http://localhost:8080/users/{{userId}}/picture
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "pictureUrl": "https://picsum.photos/256/256"
}

### update existing user
PATCH http://localhost:8080/users/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "Luigi",
  "email": "luigi@connect-play.nl"
}

### delete user
DELETE http://localhost:8080/users/2
Accept: application/json // the accept tells the server that the client expects the response in JSON format
Authorization: Bearer {{auth_token}}